version: "3.8"

services:
  api:
    build:
      args:
        user: ${UID:-1000}
        uid: ${UID:-1000}
        WWWUSER: ${UID:-1000}
        WWWGROUP: ${GID:-1000}
      context: ./api
      dockerfile: Dockerfile
    container_name: payapp-site-api
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
      - ./api/.env:/var/www/html/.env
      - ./api/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./configs/certs/leashpay.test.crt:/etc/ssl/certs/leashpay.test.crt
      - ./configs/certs/leashpay.test.key:/etc/ssl/private/leashpay.test.key
      - ./configs/nginx/nginx.conf:/etc/nginx/sites-enabled/default
      - ./configs/nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - api-db
    ports:
      - "8095:80"
      - "8096:443"
    env_file:
      - ./api/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    labels:
      - "traefik.enable=true"
    networks:
      - payapp

  api-db:
    image: mariadb:10.5
    container_name: payapp-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${API_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${API_DB_PASSWORD}
      MYSQL_PASSWORD: ${API_DB_PASSWORD}
      MYSQL_USER: ${API_DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./configs/mysql:/docker-entrypoint-initdb.d
      - ./configs/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - payapp

  web:
    build:
      args:
        user: ${UID:-1000}
        uid: ${UID:-1000}
        WWWUSER: ${UID:-1000}
        WWWGROUP: ${GID:-1000}
      context: ./site
      dockerfile: Dockerfile
    container_name: payapp-site-web
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./site:/app
    command: npm run dev
    ports:
      - "8097:3000"
    env_file:
      - ./api/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    labels:
      - "traefik.enable=true"
    networks:
      - payapp

  webserver:
    image: nginx:alpine
    container_name: payapp-site-server
    restart: unless-stopped
    tty: true
    depends_on:
      - web
    ports:
      - "8098:80"
      - "8099:443"
    volumes:
      - ./configs/certs/leashpay.test.crt:/etc/ssl/certs/leashpay.test.crt
      - ./configs/certs/leashpay.test.key:/etc/ssl/certs/leashpay.test.key
      - ./configs/nginx/website.conf:/etc/nginx/conf.d/default.conf
    networks:
      - payapp

networks:
  payapp:
    driver: bridge
    name: payapp
